name: Ecocraft
version: '${project.version}'
main: ecocraft.ecocraft.Ecocraft
api-version: 1.19



commands:
  solar:
    description: test
    permission:

  solarbase:
    description: test
  cable:
    description: test
  where:
    description: where you are
  realTp:
    description: teleport based on real coordinates
  details:
    description: region details
  localPollution:
    description: set local pollution
