name: Ecocraft
version: '${project.version}'
main: ecocraft.ecocraft.Ecocraft
api-version: 1.19



commands:

  solar:
    description: test
  solarbase:
    description: test
  cable:
    description: test
  where:
    description: test
